packages:
  - .
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.15.0+sha512-GZqCPTPX5tlv8vT77sBFmJc2ddh4bwU83QozT5sr3yqbJDJEjfsLtisR9FizmL3WgnqZA1dCFSiAEpI84kAaRQ==
loglevel: info
minimumReleaseAgeExclude:
  - config-file-effect@0.2.1
  - json-schema-effect@0.2.2
