packages:
  - .
autoInstallPeers: true
configDependencies:
  "@savvy-web/pnpm-plugin-silk": 0.15.2+sha512-NmPfZm4W8CmiOhOf6C+c0fwU2RC7hznytvZCAow56oDExSGpHbdISL9ykhRDSPQ+iK7CCGTx8Q+ATOnOIPIUlA==
loglevel: info
